/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IGameInterface extends ethers.utils.Interface {
  functions: {
    "__callback(uint8[],uint256,uint256)": FunctionFragment;
    "supportsIGame()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "__callback",
    values: [BigNumberish[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsIGame",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "__callback", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsIGame",
    data: BytesLike
  ): Result;

  events: {};
}

export class IGame extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IGameInterface;

  functions: {
    __callback(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "__callback(uint8[],uint256,uint256)"(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    supportsIGame(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "supportsIGame()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;
  };

  __callback(
    cards: BigNumberish[],
    requestId: BigNumberish,
    bitCards: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "__callback(uint8[],uint256,uint256)"(
    cards: BigNumberish[],
    requestId: BigNumberish,
    bitCards: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  supportsIGame(overrides?: CallOverrides): Promise<boolean>;

  "supportsIGame()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    __callback(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "__callback(uint8[],uint256,uint256)"(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsIGame(overrides?: CallOverrides): Promise<boolean>;

    "supportsIGame()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    __callback(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "__callback(uint8[],uint256,uint256)"(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    supportsIGame(overrides?: CallOverrides): Promise<BigNumber>;

    "supportsIGame()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    __callback(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "__callback(uint8[],uint256,uint256)"(
      cards: BigNumberish[],
      requestId: BigNumberish,
      bitCards: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    supportsIGame(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "supportsIGame()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
