/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IOracleInterface extends ethers.utils.Interface {
  functions: {
    "acceptRandomNumberRequest(uint256)": FunctionFragment;
    "createRandomNumberRequest()": FunctionFragment;
    "supportsIOracle()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptRandomNumberRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRandomNumberRequest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsIOracle",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptRandomNumberRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRandomNumberRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsIOracle",
    data: BytesLike
  ): Result;

  events: {};
}

export class IOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IOracleInterface;

  functions: {
    acceptRandomNumberRequest(
      requestId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "acceptRandomNumberRequest(uint256)"(
      requestId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createRandomNumberRequest(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createRandomNumberRequest()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    supportsIOracle(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "supportsIOracle()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;
  };

  acceptRandomNumberRequest(
    requestId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "acceptRandomNumberRequest(uint256)"(
    requestId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createRandomNumberRequest(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createRandomNumberRequest()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  supportsIOracle(overrides?: CallOverrides): Promise<boolean>;

  "supportsIOracle()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    acceptRandomNumberRequest(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "acceptRandomNumberRequest(uint256)"(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createRandomNumberRequest(overrides?: CallOverrides): Promise<BigNumber>;

    "createRandomNumberRequest()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsIOracle(overrides?: CallOverrides): Promise<boolean>;

    "supportsIOracle()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    acceptRandomNumberRequest(
      requestId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "acceptRandomNumberRequest(uint256)"(
      requestId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createRandomNumberRequest(overrides?: Overrides): Promise<BigNumber>;

    "createRandomNumberRequest()"(overrides?: Overrides): Promise<BigNumber>;

    supportsIOracle(overrides?: CallOverrides): Promise<BigNumber>;

    "supportsIOracle()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptRandomNumberRequest(
      requestId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "acceptRandomNumberRequest(uint256)"(
      requestId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createRandomNumberRequest(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createRandomNumberRequest()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    supportsIOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "supportsIOracle()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
